"""Eliminar campo estado de Producto

Revision ID: a13fa475682a
Revises: 4fb264f295cb
Create Date: 2025-07-28 22:25:14.822465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a13fa475682a'
down_revision = '4fb264f295cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
